INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(100, 'Nick', 'Jonnas', 'nick.jonnas@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(101, 'Bill', 'Garry', 'bill.garry@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(102, 'Alex', 'Staler', 'alex.staler@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(103, 'Whitney', 'Simmons', 'whitney.simmons@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(104, 'Cassndra', 'Martin', 'cass.martin@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(105, 'Alex', 'Silver', 'alex.silver@gmail.com', sysdate());
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE) VALUES(106, 'Jym', 'Stopani', 'jym.stopani@gmail.com', sysdate());
INSERT INTO POST VALUES(200, 'my first comment', 100);
INSERT INTO POST VALUES(201, 'my first comment', 101);
INSERT INTO POST VALUES(202, 'my second comment', 101);
INSERT INTO POST VALUES(203, 'my first comment', 102);
INSERT INTO POST VALUES(204, 'my second comment', 102);
INSERT INTO POST VALUES(205, 'my first comment', 103);
INSERT INTO POST VALUES(206, 'my first comment', 104);
INSERT INTO POST VALUES(207, 'my first comment', 105);
INSERT INTO POST VALUES(208, 'my first comment', 106);
